apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: chaos-appinstance
  namespace: default
spec:
  # It can be active/stop
  engineState: 'active'
  appinfo:
    appns: ''
    applabel: ''
    appkind: ''
  chaosServiceAccount: litmus-admin
  experiments:
    - name: unmap-route
      spec:
        components:
          env:
            # provide the total chaos duration
            - name: TOTAL_CHAOS_DURATION
              value: '20'

            # provide the chaos interval
            - name: CHAOS_INTERVAL
              value: '10'

            - name: APP_NAME
              value: 'hello-spring-cloud'

            - name: ORG_NAME
              value: 'POV'

            - name: SPACE_NAME
              value: 'appchaos'

            - name: HOSTNAME
              value: 'hello_spring_cloud'

            - name: SECRET_NAME
              value: 'cloud-foundry-credentials'






